# Generated by Django 2.2.2 on 2019-09-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='text',
            field=models.TextField(max_length=200, unique=True),
        ),
    ]
